Group11/urls.py
# type: ignore
"""Group11 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django import urls
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as authViews


from .views import home_page

from users.views import(
    users_list,
    Register,
    loginpage,
    logoutpage,
)

from room.views import(
    create_room,
    update_room,
    delete_room,
    
)

from blog.views import(
    create_answer,
    inside_room,
    update_blog,
    delete_blog,
    like_blog,
    like_answer,
    delete_answer,
)

admin.site.site_url = None  # Removes the 'View Site' link
admin.site.site_header = 'Corona-Overflow'

urlpatterns = [
    #reset password
    path('password-reset/', authViews.PasswordResetView.as_view(), name="password_reset"),
    path('password-reset-done/', authViews.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', authViews.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', authViews.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    #Registeration
    path('users/', users_list, name='users'),
    path('', home_page ),
    path('register/', Register , name='Register'),
    path('login/', loginpage , name='loginpage'),
    path('logout/', logoutpage , name='logout'),


    #Room
    path('home/create-room/', create_room , name='create-room'),
    path('home/update-room/<str:name>/', update_room , name='update-room'),
    path('home/delete-room/<str:name>/', delete_room , name='delete-room'),
    path('home/room/<str:name>/', inside_room , name='inside-room'),


    #blog
    path('home/room/<str:name>/<int:pk>/', create_answer , name='create_answer'),
    path('home/room/update_blog/<str:name>/<int:pk>/', update_blog , name='update-blog'),
    path('home/room/delete_blog/<str:name>/<int:pk>/', delete_blog , name='delete-blog'),
    path('home/room/like/<str:name>/<int:pk>/', like_blog , name='like'),

    #answer
    path('home/room/likeanswer/<str:name>/<int:pk>/', like_answer , name='likeanswer'),
    path('home/room/delete_answer/<str:name>/<int:pk>/', delete_answer , name='delete-answer'),

    
    #home page
    path('home/', home_page , name='home'),

    #admin
    path('admin/', admin.site.urls, name='admin'),

]

room/models.py
# type: ignore
from django.db import models
from django import forms
from users.models import user

# Create your models here.


class room(models.Model):
    CHOICES = (
        ('SE', 'Software Engineering'),
        ('EE', 'Electrical Engineering'),
        ('CE', 'Chemical Engineering'),
        ('Ce', 'Civil Engineering'),
        ('ME', 'Mechanical Engineering'),
    )
    creator = models.CharField(max_length=100,null=False,default='abedgh')
    name = models.CharField(max_length=100,null=False,primary_key=True)
    students = models.ManyToManyField(user)
    subject = models.CharField(max_length=300, choices = CHOICES,default=CHOICES[0][0],null=True)

Group11/forms.py
# type: ignore
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import PasswordInput,SelectMultiple

from users.models import user

from room.models import room

from blog.models import answer
from blog.models import blog



class RoomModelForm(forms.ModelForm):
    students= forms.ModelMultipleChoiceField(queryset=None)
    class Meta:
        model = room
        fields = ['name','students']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Choose a name','class': 'form-control input-text'}),
        }


    def __init__ (self,u,  *args, **kwargs):
        super(RoomModelForm, self).__init__(*args, **kwargs)
        self.fields["students"].widget = forms.widgets.CheckboxSelectMultiple(attrs={'class':'lst'})
        self.fields["students"].help_text = "These sudents matches your subject!"
        self.fields["students"].queryset = user.objects.filter(is_teacher=False,subject=u.subject)





class RegisterForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control input-text'})
        self.fields['password2'].widget = PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'form-control input-text'})
    

    class Meta:
        model = user
        fields = ['email','username','password1','password2','subject','is_teacher']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control input-text','placeholder': 'Email Adress'}),
            'username': forms.TextInput(attrs={'class': 'form-control input-text','placeholder': 'Username'}),
            'is_teacher': forms.CheckboxInput(attrs={'class': 'checkbx'}),
            'subject': forms.Select(attrs={'class': 'form-control input-text'}),
        }
        

class BlogModelForm(forms.ModelForm):
    class Meta:
        model = blog
        fields = ['question']
        widgets = {
            'question': forms.Textarea(attrs={'class': 'form-control input-text','placeholder': 'Your Question','rows':4}),
        }


class AnswerModelForm(forms.ModelForm):
    class Meta:
        model = answer
        fields = ['answer']
        widgets = {
            'answer': forms.TextInput(attrs={'class': 'form-control input-text answer','placeholder': 'Add a comment'}),
        }

Group11/views.py
# type: ignore
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponseRedirect
from django.urls import reverse

from users.models import user

from room.models import room

@login_required(login_url='loginpage')
def home_page(request):
    if request.user.is_superuser:
        return HttpResponseRedirect(reverse('admin:index'))
    obj = user.objects.filter(username=request.user).first()
    if obj.is_teacher:  
        rooms = room.objects.filter(creator=obj)
    else:
        rooms = room.objects.filter(students__username=request.user.username)
    size = rooms.__len__()
    content = {'obj':obj , 'rooms':rooms , 'size':size}
    return render(request, "home_page.html", content)

Group11/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'logo.jpg' %}" type="image/jpg" sizes="16x16">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">


    {% block style %}{% endblock %}

    <title> {% block page-title %}{% endblock %} </title>
</head>

<body>

    <div class="topnav" id="myTopnav">
            <a style="margin: 0;" href=".">   <span class="xl">Corona Overflow</span></a>
            {% block nav-items %}{% endblock %}
            <a class="newroom fr" href="{% url 'logout' %}" > <i class="fa fa-sign-out" style="font-size:20px"></i> Logout</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
            </a>
        
    </div>
    <div class="title">{% block title %}{% endblock %}</div>
    {% block content %}
        
    {% endblock %}

    <script>
        function myFunction() {
          var x = document.getElementById("myTopnav");
          if (x.className === "topnav") {
            x.className += " responsive";
          } else {
            x.className = "topnav";
          }
        }
    </script>
</body>
</html>

Group11/templates/create_room.html
{% extends "base.html" %}

{% block title %} {% if edit %} Edit Room {% else %} Create Room {% endif %} {% endblock %}

{% block page-title %}{% if edit %} Edit Room {% else %}Create Room{% endif %}{% endblock %}

<!-- nar items buttons -->
{% block nav-items %}
    <a href="{% url 'home' %}" class="newroom">Home</a>
    <a href="." class="newroom">Create room</a>
{% endblock %}

<!-- style -->
{% block style %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/create_room.css' %}">
{% endblock %}


{% block content %}

    <form method="post" enctype='multipart/form-data' action="" style="background-color: rgba(255, 255, 255, 0); width: 100%; text-align: center; ">
        {% csrf_token %}  

        

        <h1 style=" color: #3b5998;">Room's Name :</h1>
        {% if edit %} <h1>{{name}}<div style="display: none;">{{form.name}}</div></h1> {% else %} <h1>{{form.name}}</h1> {% endif %}
        <span style="color: red;">{{ form.name.errors }}</span>

        <h1 style=" color: #3b5998;">Select Students:</h1>
        <span style="color: red;">{{ form.students.errors }}</span>
        <h1 style="text-align: left;">{{form.students}}</h1>
        <button  type="submit" class="btn btn-black">Submit</button>
    </form>
{% endblock %}

Group11/templates/delete_room.html
{% extends "base.html" %}

{% block title %}  {% if edit1 %} Delete Question {% else %} Delete Room {% endif %} {% endblock %}

{% block page-title %}{% if edit1 %} Delete Question {% else %} Delete Room {% endif %} {% endblock %}

<!-- nar items buttons -->
{% block nav-items %}
    <a href="{% url 'home' %}" class="newroom" style=" margin-left: 20px;">Home</a>
{% endblock %}

<!-- style -->
{% block style %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/delete_room.css' %}">

{% endblock %}


{% block content %}

    <form method="post" enctype='multipart/form-data' action="" style="background-color: rgba(255, 255, 255, 0); width: 50%; text-align: center; margin: auto;">
        {% csrf_token %}   


        <h1  style=" color: #3b5998;" >Are you sure you want to delete <span style=" color: red" >{{name}}</span> ? </h1>


        <button  type="submit" class="btn">Delete</button>
    </form>
{% endblock %}

Group11/templates/home_page.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block page-title %}Home Page{% endblock %}

<!-- style -->
{% block style %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/home_page.css' %}">

{% endblock %}

<!-- nar items buttons -->
{% block nav-items %}
    <a href="." class="newroom">Home</a>
    {% if obj.is_teacher %}
        <a href="{% url 'create-room' %}" class="newroom">Create room</a>

    {% endif %}
{% endblock %}

{% block content %}
    <table style="width: 90%; margin: 25px; ">
        <thead>
            <tr style="font-size: 50px; color: #3b5998;">
                <td style="width: 70%; text-align: center; " > <span > Rooms </span></td>
                <td style="text-align: center; border-bottom: 1px solid #3b5998;">Profile</td>
            </tr>
            <tr>
                <td style="vertical-align: top;">
                    {% if size == 0 %}
                        <div style="text-align: center; font-size: 80px; font-weight: 700; color: red; margin-top: 50px;">
                            You are not in any room.
                        </div>
                    {% endif %}
                    {% for room in rooms %}
                        <div class="room" >
                            <a  href="{% url 'inside-room' room.name %}" style="font-size: 50px;  display: block; color:hsla(0, 100%, 100%, 0.88) ;" >
                                {{room.name}}
                            </a>
                            <span style="vertical-align: text-top; font-size: 15px; color: gray;">
                                <span style="color: green;">Teacher: {{room.creator}}</span>
                                | <span style="color: green;"> {{room.get_subject_display}} </span>
                                {% if obj.is_teacher %} | <a href="{% url 'update-room' room.name %}">Edit</a> |{% endif %} 
                                {% if obj.is_teacher %}<a style="color:red;" href="{% url 'delete-room' room.name %}">Delete</a>{% endif %}
                            </span>
                        </div>
                    {% endfor %}
                </td>
                <td  style="padding-left:10px ; vertical-align: top; text-align: center;">
                    {% if obj.is_teacher %}
                        <p style="font-size: 30px; margin: 10px; padding: 10px;">Teacher</p>
                    {% else %}
                        <p style="font-size: 30px; margin: 10px; padding: 10px;">Student</p>
                    {% endif %}
                    <b>Email</b>
                        <p>{{ obj.email }} </p>
                    <b>Username</b>
                        <p>{{ obj.username }} </p>
                    <b>Subject</b>
                        <p>{{ obj.get_subject_display }} </p>
                    {% if not obj.is_teacher %}
                    <p > <b> Year  </b>{{ obj.year }} </p> 
                    {% endif %}
                    <p> <b> Number of rooms you are in  </b>{{ size }} </p>
                </td>
            </tr>
        </thead>
    </table>
{% endblock %}

Group11/templates/inside_room.html
{% extends "base.html" %}

{% block title %} {{name}} {% endblock %}

{% block page-title %} {{name}} {% endblock %}

<!-- style -->
{% block style %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/inside_room.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% endblock %}

<!-- nar items buttons -->
{% block nav-items %}
    <a href="{% url 'home' %}" class="newroom" style=" margin-left: 20px;">Home</a>
    {% if obj.is_teacher %}
        <a href="{% url 'create-room' %}" class="newroom" style="margin-left: 20px;">Create room</a>
    {% endif %}

{% endblock %}

{% block content %}

{% if not obj.is_teacher %}
<form style="text-align: center;" class="room" method="post" action=".">
    {% csrf_token %}
    <div style="font-size: 40px; color: green;">Ask a Question</div>
    {{form.question}}
    <button style="margin: 15px;"  type="submit" class="btn btn-black">Post</button>
</form>

{% endif %}

{% for blog in blogs %}
<div class="room" >
    <div style="font-size: 40px; color:hsla(0, 100%, 100%, 0.88) ; display: block;" >
        <div style="color: #3b5998; text-align: center; font-size: larger;">Question from <span style="color:#4971c8; text-decoration: underline; font-weight: 700;">{{blog.creator}}</span> </div>
        <div > {{blog.question}}</div>
        <div style="margin-bottom: 10px; text-align: center; color: #3b5998; width: 100%; border-bottom: 1px solid #3b5998;">Comments</div>
        {% for answer in answers %}
            {% if  answer.question == blog %}
            <div>
                <div style="display: inline-block;  font-size: 20px;">
                    <div>
                        <div style="display: inline-block; color: #3b5998;">{{answer.creator}}</div>
                         : {{answer.answer}} 
                    </div>
                     <span style="   font-size: 15px; color: green;">
                        {{ answer.date }}
                    </span>
                    {% if obj.username == answer.creator.username %} | <a style="color:red; font-size: 15px;" href="{% url 'delete-answer' name answer.pk %}">Delete</a>{% endif %}
                    | <a style="font-size: 15px;" href="{% url 'likeanswer' name answer.pk %}" class="fa fa-thumbs-up faa"> {{ answer.likes }} Like</a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        
        <form style="text-align: center; margin-top: 10px;"  method="post" action={% url 'create_answer' name blog.pk %}>
            {% csrf_token %}
            {{form1.answer}}
            <button style="margin: 15px; width: 100px;"  type="submit" class="btn btn-black">Comment</button>
        </form>
        
        <span style=" display: block;  font-size: 20px; color: white;">
            <span style="color: green;"> Post Date : {{ blog.date }}</span>
            {% if obj.username == blog.creator.username %} | <a href="{% url 'update-blog' name blog.pk %}">Edit</a> {% endif %} 
            {% if obj.username == blog.creator.username or obj.is_teacher %} | <a style="color:red;" href="{% url 'delete-blog' name blog.pk %}">Delete</a>{% endif %}
            | <a href="{% url 'like' name blog.pk %}" class="fa fa-thumbs-up faa"> {{ blog.likes }} Likes</a>
        </span>
    </div>
</div>
{% endfor %}

<script>
    function myFunction(x) {
      x.classList.toggle("fa-thumbs-down");
    }
</script>
{% endblock %}

Group11/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'logo.jpg' %}" type="image/jpg" sizes="16x16">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    
    <link type="text/css" rel="stylesheet" href="{% static 'css/login.css' %}">

    <title>Login</title>
</head>
<body>
    <div class="sidenav">
        <div class="login-main-text">
            <h1 class="name" >Corona Over-Flow</h1>
            <h3>Login Page</h3>
            <p>Login from here to access.</p>
        </div>
    </div>
    
    <div class="main">
        <div class="col-md-6 col-sm-12">
           <div class="login-form">
              <form method="POST" action="">
                {% csrf_token %}
                 <div class="form-group">
                    <label>User Name</label>
                    <input type="text" name="username" class="form-control" placeholder="User Name">
                 </div>
                 <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" placeholder="Password">
                 </div>
                 {% for m in messages %}
                    <h4 style="color: red;">{{m}}</h4>
                 {% endfor %}
                 <button type="submit" class="btn btn-black">Login</button>
              </form>
                <div>
                    New here?<a href="{% url 'Register' %}" >Register</a>
                </div>
                <div>
                    <a style="margin: 0px;" href="{% url 'password_reset' %}"  >Forgot your password?</a>
                </div>
           </div>
        </div>
        
    </div>
</body>
</html>

Group11/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="icon" href="{% static 'logo.jpg' %}" type="image/jpg" sizes="16x16">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    
    <link rel="stylesheet" href="{% static 'css/Register.css' %}">

    <title>Register</title>
</head>
<body>
    <div class="sidenav">
        <div class="login-main-text">
            <h1>Corona Over-Flow</h1>
            <h3>Register Page</h3>
           <p>Register from here to access.</p>
        </div>
    </div>
    <div class="main">
        <div class="col-md-6 col-sm-12">
           <div class="login-form">
              <form method="POST" action="">
                
                {% csrf_token %}
                {% for field in form %}
                    <div style="padding: 0; margin: 0;">{{ field.label_tag }}</div>
                    <div style="margin: 0 0 20px 0; ">{{ field }}</div><span style="color: red;">{{ field.errors }}</span>
                {% endfor %}
                <div style="display: inline-block;">
                    <button type="submit" class="btn btn-secondary">Register</button>
                </div>
                <div style="float: right;">
                    Already Signed up?<a href="{% url 'loginpage' %}"  >Login</a>
                </div>
              </form>
              
           </div>
        </div>
    </div>
</body>
</html>

Group11/templates/update_blog.html
{% extends "base.html" %}

{% block title %} Update Question {% endblock %}

{% block page-title %}Update Question{% endblock %}

<!-- nar items buttons -->
{% block nav-items %}
    <a href="{% url 'home' %}" class="newroom" style=" margin-left: 20px;">Home</a>
{% endblock %}

<!-- style -->
{% block style %}
<style>

    .btn{
        color: white;
        background-color: black;
    }
    .btn:hover{
        color: black;
        background-color: white;
        cursor: pointer;
    }
    .text-input{
        width: 40%;
        height: 70px;
    }
</style>
{% endblock %}


{% block content %}

    <form method="post"  action="" style="background-color: rgba(255, 255, 255, 0); width: 60%; text-align: center; margin: auto;">
        {% csrf_token %}   

        <div style="margin: 30px; font-size: 50px;"> Your new question  </div>
        {{form.question}}


        <button style="margin: 30px;" type="submit" class="btn">Commit changes</button>
    </form>
{% endblock %}

Group11/templates/users_list.html
{% extends "base.html" %}

{% block title %} Users list {% endblock %}

{% block style %}
    <style>
        table{
            border: 1px solid grey;
            margin: 0 auto;
            margin-top: 80px;
            border-collapse: collapse;
            border-radius: 10px;
        }
        td{
            border: 1px solid grey;
            text-align: center;
            padding: 8px;
        }
        td:hover{
            background-color: rgb(223, 223, 223);
        }
        tr:hover{
           background-color: rgb(207, 207, 207);
        }
        th{
            padding: 10px;
            font-family: cursive;
            font-size: 20px;
            color: #3b5998;
        }
    </style>
{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>Full name</th>
                <th>Email</th>
                <th>Username</th>
                <th>Is Teacher</th>
            </tr>
        </thead>
        <tbody>
            {% for user in objects %}
            <tr> 
                <td>{{user.fullname}}</td>
                <td>{{user.email}}</td>
                <td>{{user.username}}</td>
                <td>{{user.is_teacher}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}